// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_songs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSongGenre = `-- name: AddSongGenre :exec
INSERT INTO song_genres (song_id, genre_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddSongGenreParams struct {
	SongID  pgtype.UUID `json:"song_id"`
	GenreID pgtype.UUID `json:"genre_id"`
}

func (q *Queries) AddSongGenre(ctx context.Context, arg AddSongGenreParams) error {
	_, err := q.db.Exec(ctx, addSongGenre, arg.SongID, arg.GenreID)
	return err
}

const clearSongGenres = `-- name: ClearSongGenres :exec
DELETE FROM song_genres WHERE song_id = $1
`

func (q *Queries) ClearSongGenres(ctx context.Context, songID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearSongGenres, songID)
	return err
}

const createGenre = `-- name: CreateGenre :one
INSERT INTO genres (id, name) VALUES ($1, $2) RETURNING id, name
`

type CreateGenreParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) CreateGenre(ctx context.Context, arg CreateGenreParams) (Genre, error) {
	row := q.db.QueryRow(ctx, createGenre, arg.ID, arg.Name)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getGenreByName = `-- name: GetGenreByName :one
SELECT id, name FROM genres WHERE name = $1
`

func (q *Queries) GetGenreByName(ctx context.Context, name string) (Genre, error) {
	row := q.db.QueryRow(ctx, getGenreByName, name)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listAdminSongs = `-- name: ListAdminSongs :many
SELECT s.id, s.title, s.duration_ms, s.created_at,
  ar.name AS artist_name, al.title AS album_title, sa.provider AS storage_provider
FROM songs s
JOIN artists ar ON ar.id = s.artist_id
LEFT JOIN albums al ON al.id = s.album_id
JOIN storage_files sf ON sf.id = s.storage_file_id
JOIN storage_accounts sa ON sa.id = sf.storage_account_id
WHERE s.deleted_at IS NULL
  AND (
    $1::text IS NULL
    OR s.title ILIKE '%' || $1::text || '%'
    OR ar.name ILIKE '%' || $1::text || '%'
  )
  AND (
    $2::timestamptz IS NULL
    OR (s.created_at, s.id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY s.created_at DESC, s.id DESC
LIMIT $4
`

type ListAdminSongsParams struct {
	Search          *string            `json:"search"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	LimitCount      int32              `json:"limit_count"`
}

type ListAdminSongsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	DurationMs      int32              `json:"duration_ms"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ArtistName      string             `json:"artist_name"`
	AlbumTitle      *string            `json:"album_title"`
	StorageProvider string             `json:"storage_provider"`
}

// Sprint 14 admin Manage Songs (ADR 0010) — search by title or artist
// name, same cursor-pagination shape used everywhere else in this API.
func (q *Queries) ListAdminSongs(ctx context.Context, arg ListAdminSongsParams) ([]ListAdminSongsRow, error) {
	rows, err := q.db.Query(ctx, listAdminSongs,
		arg.Search,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminSongsRow
	for rows.Next() {
		var i ListAdminSongsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.DurationMs,
			&i.CreatedAt,
			&i.ArtistName,
			&i.AlbumTitle,
			&i.StorageProvider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSong = `-- name: SoftDeleteSong :execrows
UPDATE songs SET deleted_at = now(), updated_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteSong(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteSong, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSongArtistAlbum = `-- name: UpdateSongArtistAlbum :exec
UPDATE songs SET artist_id = $2, album_id = $3, updated_at = now() WHERE id = $1
`

type UpdateSongArtistAlbumParams struct {
	ID       pgtype.UUID `json:"id"`
	ArtistID pgtype.UUID `json:"artist_id"`
	AlbumID  pgtype.UUID `json:"album_id"`
}

func (q *Queries) UpdateSongArtistAlbum(ctx context.Context, arg UpdateSongArtistAlbumParams) error {
	_, err := q.db.Exec(ctx, updateSongArtistAlbum, arg.ID, arg.ArtistID, arg.AlbumID)
	return err
}

const updateSongTitle = `-- name: UpdateSongTitle :exec
UPDATE songs SET title = $2, updated_at = now() WHERE id = $1
`

type UpdateSongTitleParams struct {
	ID    pgtype.UUID `json:"id"`
	Title string      `json:"title"`
}

func (q *Queries) UpdateSongTitle(ctx context.Context, arg UpdateSongTitleParams) error {
	_, err := q.db.Exec(ctx, updateSongTitle, arg.ID, arg.Title)
	return err
}
