// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: albums.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums (id, artist_id, title, cover_url, released_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, artist_id, title, cover_url, released_at, created_at, updated_at
`

type CreateAlbumParams struct {
	ID         pgtype.UUID `json:"id"`
	ArtistID   pgtype.UUID `json:"artist_id"`
	Title      string      `json:"title"`
	CoverUrl   *string     `json:"cover_url"`
	ReleasedAt pgtype.Date `json:"released_at"`
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, createAlbum,
		arg.ID,
		arg.ArtistID,
		arg.Title,
		arg.CoverUrl,
		arg.ReleasedAt,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Title,
		&i.CoverUrl,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlbumByArtistAndTitle = `-- name: GetAlbumByArtistAndTitle :one
SELECT id, artist_id, title, cover_url, released_at, created_at, updated_at FROM albums WHERE artist_id = $1 AND title = $2
`

type GetAlbumByArtistAndTitleParams struct {
	ArtistID pgtype.UUID `json:"artist_id"`
	Title    string      `json:"title"`
}

func (q *Queries) GetAlbumByArtistAndTitle(ctx context.Context, arg GetAlbumByArtistAndTitleParams) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumByArtistAndTitle, arg.ArtistID, arg.Title)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Title,
		&i.CoverUrl,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlbumByID = `-- name: GetAlbumByID :one
SELECT id, artist_id, title, cover_url, released_at, created_at, updated_at FROM albums WHERE id = $1
`

func (q *Queries) GetAlbumByID(ctx context.Context, id pgtype.UUID) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumByID, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.ArtistID,
		&i.Title,
		&i.CoverUrl,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
