// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStorageGrowth = `-- name: GetStorageGrowth :many
SELECT month::timestamptz AS month, COALESCE(sum(sf.size_bytes), 0)::bigint AS total_bytes
FROM generate_series(
  date_trunc('month', now()) - interval '5 months',
  date_trunc('month', now()),
  interval '1 month'
) AS month
LEFT JOIN storage_files sf ON date_trunc('month', sf.created_at) = month
GROUP BY month
ORDER BY month
`

type GetStorageGrowthRow struct {
	Month      pgtype.Timestamptz `json:"month"`
	TotalBytes int64              `json:"total_bytes"`
}

// One row per month for the last 6 months (including the current one),
// zero-filled via generate_series so a quiet month still shows up as a
// bar at 0 instead of vanishing from the chart.
func (q *Queries) GetStorageGrowth(ctx context.Context) ([]GetStorageGrowthRow, error) {
	rows, err := q.db.Query(ctx, getStorageGrowth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStorageGrowthRow
	for rows.Next() {
		var i GetStorageGrowthRow
		if err := rows.Scan(&i.Month, &i.TotalBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopPlayedSongs = `-- name: GetTopPlayedSongs :many
SELECT s.id, s.title, ar.name AS artist_name, count(h.id) AS play_count
FROM play_history h
JOIN songs s ON s.id = h.song_id
JOIN artists ar ON ar.id = s.artist_id
GROUP BY s.id, s.title, ar.name
ORDER BY play_count DESC, s.title ASC
LIMIT $1
`

type GetTopPlayedSongsRow struct {
	ID         pgtype.UUID `json:"id"`
	Title      string      `json:"title"`
	ArtistName string      `json:"artist_name"`
	PlayCount  int64       `json:"play_count"`
}

func (q *Queries) GetTopPlayedSongs(ctx context.Context, limit int32) ([]GetTopPlayedSongsRow, error) {
	rows, err := q.db.Query(ctx, getTopPlayedSongs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopPlayedSongsRow
	for rows.Next() {
		var i GetTopPlayedSongsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistName,
			&i.PlayCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
