// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artists.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArtist = `-- name: CreateArtist :one
INSERT INTO artists (id, name, image_url) VALUES ($1, $2, $3) RETURNING id, name, image_url, created_at, updated_at, musicbrainz_id
`

type CreateArtistParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	ImageUrl *string     `json:"image_url"`
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, createArtist, arg.ID, arg.Name, arg.ImageUrl)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MusicbrainzID,
	)
	return i, err
}

const getArtistByID = `-- name: GetArtistByID :one
SELECT id, name, image_url, created_at, updated_at, musicbrainz_id FROM artists WHERE id = $1
`

func (q *Queries) GetArtistByID(ctx context.Context, id pgtype.UUID) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByID, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MusicbrainzID,
	)
	return i, err
}

const getArtistByName = `-- name: GetArtistByName :one
SELECT id, name, image_url, created_at, updated_at, musicbrainz_id FROM artists WHERE name = $1
`

func (q *Queries) GetArtistByName(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByName, name)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MusicbrainzID,
	)
	return i, err
}

const updateArtistMusicbrainzID = `-- name: UpdateArtistMusicbrainzID :exec
UPDATE artists SET musicbrainz_id = $2, updated_at = now()
WHERE id = $1 AND musicbrainz_id IS NULL
`

type UpdateArtistMusicbrainzIDParams struct {
	ID            pgtype.UUID `json:"id"`
	MusicbrainzID *string     `json:"musicbrainz_id"`
}

// Only fills a still-empty musicbrainz_id — never overwrites a value set
// by an earlier, possibly more specific match.
func (q *Queries) UpdateArtistMusicbrainzID(ctx context.Context, arg UpdateArtistMusicbrainzIDParams) error {
	_, err := q.db.Exec(ctx, updateArtistMusicbrainzID, arg.ID, arg.MusicbrainzID)
	return err
}
