// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBackgroundJobsSummary = `-- name: GetBackgroundJobsSummary :many
SELECT status, count(*) AS job_count FROM ingest_jobs GROUP BY status
`

type GetBackgroundJobsSummaryRow struct {
	Status   string `json:"status"`
	JobCount int64  `json:"job_count"`
}

func (q *Queries) GetBackgroundJobsSummary(ctx context.Context) ([]GetBackgroundJobsSummaryRow, error) {
	rows, err := q.db.Query(ctx, getBackgroundJobsSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBackgroundJobsSummaryRow
	for rows.Next() {
		var i GetBackgroundJobsSummaryRow
		if err := rows.Scan(&i.Status, &i.JobCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
  (SELECT count(*) FROM songs) AS total_songs,
  (SELECT count(*) FROM users) AS total_users,
  (SELECT count(*) FROM storage_accounts) AS total_drives,
  (SELECT COALESCE(sum(used_bytes), 0)::bigint FROM storage_accounts) AS total_storage_bytes
`

type GetDashboardStatsRow struct {
	TotalSongs        int64 `json:"total_songs"`
	TotalUsers        int64 `json:"total_users"`
	TotalDrives       int64 `json:"total_drives"`
	TotalStorageBytes int64 `json:"total_storage_bytes"`
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.TotalSongs,
		&i.TotalUsers,
		&i.TotalDrives,
		&i.TotalStorageBytes,
	)
	return i, err
}

const listStorageDistribution = `-- name: ListStorageDistribution :many
SELECT id, label, used_bytes, quota_bytes FROM storage_accounts ORDER BY label ASC
`

type ListStorageDistributionRow struct {
	ID         pgtype.UUID `json:"id"`
	Label      string      `json:"label"`
	UsedBytes  int64       `json:"used_bytes"`
	QuotaBytes *int64      `json:"quota_bytes"`
}

func (q *Queries) ListStorageDistribution(ctx context.Context) ([]ListStorageDistributionRow, error) {
	rows, err := q.db.Query(ctx, listStorageDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStorageDistributionRow
	for rows.Next() {
		var i ListStorageDistributionRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.UsedBytes,
			&i.QuotaBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
