// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHistoryEntry = `-- name: CreateHistoryEntry :one
INSERT INTO play_history (id, user_id, song_id, progress_ms, played_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, user_id, song_id, progress_ms, played_at
`

type CreateHistoryEntryParams struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	SongID     pgtype.UUID `json:"song_id"`
	ProgressMs int32       `json:"progress_ms"`
}

func (q *Queries) CreateHistoryEntry(ctx context.Context, arg CreateHistoryEntryParams) (PlayHistory, error) {
	row := q.db.QueryRow(ctx, createHistoryEntry,
		arg.ID,
		arg.UserID,
		arg.SongID,
		arg.ProgressMs,
	)
	var i PlayHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SongID,
		&i.ProgressMs,
		&i.PlayedAt,
	)
	return i, err
}

const listContinueListening = `-- name: ListContinueListening :many
SELECT song_id, progress_ms, played_at, duration_ms FROM (
  SELECT DISTINCT ON (h.song_id) h.song_id, h.progress_ms, h.played_at, s.duration_ms
  FROM play_history h
  JOIN songs s ON s.id = h.song_id
  WHERE h.user_id = $1
    AND h.progress_ms > 5000
    AND h.progress_ms < (s.duration_ms * 0.95)
  ORDER BY h.song_id, h.played_at DESC
) AS recent
ORDER BY played_at DESC
LIMIT $2
`

type ListContinueListeningParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

type ListContinueListeningRow struct {
	SongID     pgtype.UUID        `json:"song_id"`
	ProgressMs int32              `json:"progress_ms"`
	PlayedAt   pgtype.Timestamptz `json:"played_at"`
	DurationMs int32              `json:"duration_ms"`
}

// Most recent play per song, excluding songs barely started or basically
// finished (both would be noise in a "continue listening" widget).
func (q *Queries) ListContinueListening(ctx context.Context, arg ListContinueListeningParams) ([]ListContinueListeningRow, error) {
	rows, err := q.db.Query(ctx, listContinueListening, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContinueListeningRow
	for rows.Next() {
		var i ListContinueListeningRow
		if err := rows.Scan(
			&i.SongID,
			&i.ProgressMs,
			&i.PlayedAt,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistoryByUser = `-- name: ListHistoryByUser :many
SELECT id, user_id, song_id, progress_ms, played_at FROM play_history
WHERE user_id = $1
  AND (
    $2::timestamptz IS NULL
    OR (played_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY played_at DESC, id DESC
LIMIT $4
`

type ListHistoryByUserParams struct {
	UserID         pgtype.UUID        `json:"user_id"`
	CursorPlayedAt pgtype.Timestamptz `json:"cursor_played_at"`
	CursorID       pgtype.UUID        `json:"cursor_id"`
	LimitCount     int32              `json:"limit_count"`
}

func (q *Queries) ListHistoryByUser(ctx context.Context, arg ListHistoryByUserParams) ([]PlayHistory, error) {
	rows, err := q.db.Query(ctx, listHistoryByUser,
		arg.UserID,
		arg.CursorPlayedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayHistory
	for rows.Next() {
		var i PlayHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SongID,
			&i.ProgressMs,
			&i.PlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
