// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest_filter_rules.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIngestFilterRule = `-- name: CreateIngestFilterRule :one
INSERT INTO ingest_filter_rules (id, source_type, rule_type, value)
VALUES ($1, $2, $3, $4)
RETURNING id, source_type, rule_type, value, created_at
`

type CreateIngestFilterRuleParams struct {
	ID         pgtype.UUID `json:"id"`
	SourceType string      `json:"source_type"`
	RuleType   string      `json:"rule_type"`
	Value      string      `json:"value"`
}

func (q *Queries) CreateIngestFilterRule(ctx context.Context, arg CreateIngestFilterRuleParams) (IngestFilterRule, error) {
	row := q.db.QueryRow(ctx, createIngestFilterRule,
		arg.ID,
		arg.SourceType,
		arg.RuleType,
		arg.Value,
	)
	var i IngestFilterRule
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.RuleType,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIngestFilterRule = `-- name: DeleteIngestFilterRule :execrows
DELETE FROM ingest_filter_rules WHERE id = $1 AND source_type = $2
`

type DeleteIngestFilterRuleParams struct {
	ID         pgtype.UUID `json:"id"`
	SourceType string      `json:"source_type"`
}

func (q *Queries) DeleteIngestFilterRule(ctx context.Context, arg DeleteIngestFilterRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIngestFilterRule, arg.ID, arg.SourceType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listIngestFilterRules = `-- name: ListIngestFilterRules :many
SELECT id, source_type, rule_type, value, created_at FROM ingest_filter_rules WHERE source_type = $1 ORDER BY rule_type ASC, created_at ASC
`

func (q *Queries) ListIngestFilterRules(ctx context.Context, sourceType string) ([]IngestFilterRule, error) {
	rows, err := q.db.Query(ctx, listIngestFilterRules, sourceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestFilterRule
	for rows.Next() {
		var i IngestFilterRule
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.RuleType,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
