// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearIngestJobTempPath = `-- name: ClearIngestJobTempPath :exec
UPDATE ingest_jobs SET temp_path = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) ClearIngestJobTempPath(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearIngestJobTempPath, id)
	return err
}

const completeIngestJob = `-- name: CompleteIngestJob :exec
UPDATE ingest_jobs SET status = 'completed', song_id = $2, temp_path = NULL, updated_at = now() WHERE id = $1
`

type CompleteIngestJobParams struct {
	ID     pgtype.UUID `json:"id"`
	SongID pgtype.UUID `json:"song_id"`
}

func (q *Queries) CompleteIngestJob(ctx context.Context, arg CompleteIngestJobParams) error {
	_, err := q.db.Exec(ctx, completeIngestJob, arg.ID, arg.SongID)
	return err
}

const createIngestJob = `-- name: CreateIngestJob :one
INSERT INTO ingest_jobs (id, user_id, source_type, status, song_id, temp_path)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, source_type, status, song_id, error_message, created_at, updated_at, temp_path
`

type CreateIngestJobParams struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	SourceType string      `json:"source_type"`
	Status     string      `json:"status"`
	SongID     pgtype.UUID `json:"song_id"`
	TempPath   *string     `json:"temp_path"`
}

func (q *Queries) CreateIngestJob(ctx context.Context, arg CreateIngestJobParams) (IngestJob, error) {
	row := q.db.QueryRow(ctx, createIngestJob,
		arg.ID,
		arg.UserID,
		arg.SourceType,
		arg.Status,
		arg.SongID,
		arg.TempPath,
	)
	var i IngestJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceType,
		&i.Status,
		&i.SongID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TempPath,
	)
	return i, err
}

const deleteIngestJob = `-- name: DeleteIngestJob :execrows
DELETE FROM ingest_jobs WHERE id = $1 AND user_id = $2
`

type DeleteIngestJobParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteIngestJob(ctx context.Context, arg DeleteIngestJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIngestJob, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failIngestJob = `-- name: FailIngestJob :exec
UPDATE ingest_jobs SET status = 'failed', error_message = $2, updated_at = now() WHERE id = $1
`

type FailIngestJobParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage *string     `json:"error_message"`
}

func (q *Queries) FailIngestJob(ctx context.Context, arg FailIngestJobParams) error {
	_, err := q.db.Exec(ctx, failIngestJob, arg.ID, arg.ErrorMessage)
	return err
}

const getIngestJobByID = `-- name: GetIngestJobByID :one
SELECT id, user_id, source_type, status, song_id, error_message, created_at, updated_at, temp_path FROM ingest_jobs WHERE id = $1
`

func (q *Queries) GetIngestJobByID(ctx context.Context, id pgtype.UUID) (IngestJob, error) {
	row := q.db.QueryRow(ctx, getIngestJobByID, id)
	var i IngestJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceType,
		&i.Status,
		&i.SongID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TempPath,
	)
	return i, err
}

const listAllIngestJobs = `-- name: ListAllIngestJobs :many
SELECT id, user_id, source_type, status, song_id, error_message, created_at, updated_at, temp_path FROM ingest_jobs
WHERE ($1::text IS NULL OR status = $1)
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAllIngestJobsParams struct {
	Status          *string            `json:"status"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	LimitCount      int32              `json:"limit_count"`
}

// Sprint 14 admin Job Queue (docs/screens-spec.md #20) — same cursor
// pattern as ListIngestJobsByUser, minus the per-user scoping.
func (q *Queries) ListAllIngestJobs(ctx context.Context, arg ListAllIngestJobsParams) ([]IngestJob, error) {
	rows, err := q.db.Query(ctx, listAllIngestJobs,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestJob
	for rows.Next() {
		var i IngestJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceType,
			&i.Status,
			&i.SongID,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TempPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedIngestJobsWithTempPath = `-- name: ListCompletedIngestJobsWithTempPath :many
SELECT id, temp_path FROM ingest_jobs WHERE status = 'completed' AND temp_path IS NOT NULL LIMIT $1
`

type ListCompletedIngestJobsWithTempPathRow struct {
	ID       pgtype.UUID `json:"id"`
	TempPath *string     `json:"temp_path"`
}

// Sprint 10 garbage collector target: completed jobs still holding a
// temp_path. Deliberately excludes 'failed' jobs — RetryJob needs that
// file to still be on disk.
func (q *Queries) ListCompletedIngestJobsWithTempPath(ctx context.Context, limit int32) ([]ListCompletedIngestJobsWithTempPathRow, error) {
	rows, err := q.db.Query(ctx, listCompletedIngestJobsWithTempPath, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletedIngestJobsWithTempPathRow
	for rows.Next() {
		var i ListCompletedIngestJobsWithTempPathRow
		if err := rows.Scan(&i.ID, &i.TempPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngestJobsByUser = `-- name: ListIngestJobsByUser :many
SELECT id, user_id, source_type, status, song_id, error_message, created_at, updated_at, temp_path FROM ingest_jobs
WHERE user_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND (
    $3::timestamptz IS NULL
    OR (created_at, id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListIngestJobsByUserParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	Status          *string            `json:"status"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	LimitCount      int32              `json:"limit_count"`
}

func (q *Queries) ListIngestJobsByUser(ctx context.Context, arg ListIngestJobsByUserParams) ([]IngestJob, error) {
	rows, err := q.db.Query(ctx, listIngestJobsByUser,
		arg.UserID,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestJob
	for rows.Next() {
		var i IngestJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceType,
			&i.Status,
			&i.SongID,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TempPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markIngestJobProcessing = `-- name: MarkIngestJobProcessing :exec
UPDATE ingest_jobs SET status = 'processing', updated_at = now() WHERE id = $1
`

func (q *Queries) MarkIngestJobProcessing(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markIngestJobProcessing, id)
	return err
}

const resetIngestJobToPending = `-- name: ResetIngestJobToPending :exec
UPDATE ingest_jobs SET status = 'pending', error_message = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) ResetIngestJobToPending(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetIngestJobToPending, id)
	return err
}

const skipIngestJobByFilter = `-- name: SkipIngestJobByFilter :exec
UPDATE ingest_jobs SET status = 'skipped_by_filter', error_message = $2, temp_path = NULL, updated_at = now() WHERE id = $1
`

type SkipIngestJobByFilterParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage *string     `json:"error_message"`
}

// Sprint 14 sisipan (ADR 0008) — terminal state distinct from 'failed':
// the item was never actually broken, it just didn't match a configured
// filter rule for its source. temp_path is cleared same as a completed
// job (ADR 0008: skipped items shouldn't linger as temp files either).
func (q *Queries) SkipIngestJobByFilter(ctx context.Context, arg SkipIngestJobByFilterParams) error {
	_, err := q.db.Exec(ctx, skipIngestJobByFilter, arg.ID, arg.ErrorMessage)
	return err
}
