// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest_source_connections.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIngestSourceConnection = `-- name: CreateIngestSourceConnection :one
INSERT INTO ingest_source_connections (id, provider, label, account_email, credentials_encrypted)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, provider, label, account_email, credentials_encrypted, is_active, last_synced_at, created_at, updated_at
`

type CreateIngestSourceConnectionParams struct {
	ID                   pgtype.UUID `json:"id"`
	Provider             string      `json:"provider"`
	Label                string      `json:"label"`
	AccountEmail         *string     `json:"account_email"`
	CredentialsEncrypted string      `json:"credentials_encrypted"`
}

func (q *Queries) CreateIngestSourceConnection(ctx context.Context, arg CreateIngestSourceConnectionParams) (IngestSourceConnection, error) {
	row := q.db.QueryRow(ctx, createIngestSourceConnection,
		arg.ID,
		arg.Provider,
		arg.Label,
		arg.AccountEmail,
		arg.CredentialsEncrypted,
	)
	var i IngestSourceConnection
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Label,
		&i.AccountEmail,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIngestSourceConnection = `-- name: DeleteIngestSourceConnection :execrows
DELETE FROM ingest_source_connections WHERE id = $1
`

func (q *Queries) DeleteIngestSourceConnection(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIngestSourceConnection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIngestSourceConnectionByID = `-- name: GetIngestSourceConnectionByID :one
SELECT id, provider, label, account_email, credentials_encrypted, is_active, last_synced_at, created_at, updated_at FROM ingest_source_connections WHERE id = $1
`

func (q *Queries) GetIngestSourceConnectionByID(ctx context.Context, id pgtype.UUID) (IngestSourceConnection, error) {
	row := q.db.QueryRow(ctx, getIngestSourceConnectionByID, id)
	var i IngestSourceConnection
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Label,
		&i.AccountEmail,
		&i.CredentialsEncrypted,
		&i.IsActive,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveIngestSourceConnections = `-- name: ListActiveIngestSourceConnections :many
SELECT id, provider, label, account_email, credentials_encrypted, is_active, last_synced_at, created_at, updated_at FROM ingest_source_connections WHERE is_active = true ORDER BY created_at ASC
`

func (q *Queries) ListActiveIngestSourceConnections(ctx context.Context) ([]IngestSourceConnection, error) {
	rows, err := q.db.Query(ctx, listActiveIngestSourceConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestSourceConnection
	for rows.Next() {
		var i IngestSourceConnection
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Label,
			&i.AccountEmail,
			&i.CredentialsEncrypted,
			&i.IsActive,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngestSourceConnections = `-- name: ListIngestSourceConnections :many
SELECT id, provider, label, account_email, credentials_encrypted, is_active, last_synced_at, created_at, updated_at FROM ingest_source_connections ORDER BY created_at ASC
`

func (q *Queries) ListIngestSourceConnections(ctx context.Context) ([]IngestSourceConnection, error) {
	rows, err := q.db.Query(ctx, listIngestSourceConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestSourceConnection
	for rows.Next() {
		var i IngestSourceConnection
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Label,
			&i.AccountEmail,
			&i.CredentialsEncrypted,
			&i.IsActive,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngestSourceConnectionSync = `-- name: UpdateIngestSourceConnectionSync :exec
UPDATE ingest_source_connections SET last_synced_at = $2, updated_at = now() WHERE id = $1
`

type UpdateIngestSourceConnectionSyncParams struct {
	ID           pgtype.UUID        `json:"id"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
}

func (q *Queries) UpdateIngestSourceConnectionSync(ctx context.Context, arg UpdateIngestSourceConnectionSyncParams) error {
	_, err := q.db.Exec(ctx, updateIngestSourceConnectionSync, arg.ID, arg.LastSyncedAt)
	return err
}
