// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: library_browse.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listLibraryAlbums = `-- name: ListLibraryAlbums :many
SELECT al.id, al.title, al.cover_url, ar.name AS artist_name
FROM albums al
JOIN artists ar ON ar.id = al.artist_id
WHERE ($1::text IS NULL OR al.title ILIKE '%' || $1::text || '%' OR ar.name ILIKE '%' || $1::text || '%')
ORDER BY
  CASE WHEN $2::bool THEN al.title END ASC,
  CASE WHEN NOT $2::bool THEN al.created_at END DESC
LIMIT $3
`

type ListLibraryAlbumsParams struct {
	Search     *string `json:"search"`
	SortAlpha  bool    `json:"sort_alpha"`
	LimitCount int32   `json:"limit_count"`
}

type ListLibraryAlbumsRow struct {
	ID         pgtype.UUID `json:"id"`
	Title      string      `json:"title"`
	CoverUrl   *string     `json:"cover_url"`
	ArtistName string      `json:"artist_name"`
}

func (q *Queries) ListLibraryAlbums(ctx context.Context, arg ListLibraryAlbumsParams) ([]ListLibraryAlbumsRow, error) {
	rows, err := q.db.Query(ctx, listLibraryAlbums, arg.Search, arg.SortAlpha, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLibraryAlbumsRow
	for rows.Next() {
		var i ListLibraryAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CoverUrl,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryArtists = `-- name: ListLibraryArtists :many
SELECT id, name, image_url
FROM artists
WHERE ($1::text IS NULL OR name ILIKE '%' || $1::text || '%')
ORDER BY
  CASE WHEN $2::bool THEN name END ASC,
  CASE WHEN NOT $2::bool THEN created_at END DESC
LIMIT $3
`

type ListLibraryArtistsParams struct {
	Search     *string `json:"search"`
	SortAlpha  bool    `json:"sort_alpha"`
	LimitCount int32   `json:"limit_count"`
}

type ListLibraryArtistsRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	ImageUrl *string     `json:"image_url"`
}

func (q *Queries) ListLibraryArtists(ctx context.Context, arg ListLibraryArtistsParams) ([]ListLibraryArtistsRow, error) {
	rows, err := q.db.Query(ctx, listLibraryArtists, arg.Search, arg.SortAlpha, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLibraryArtistsRow
	for rows.Next() {
		var i ListLibraryArtistsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ImageUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibrarySongs = `-- name: ListLibrarySongs :many

SELECT s.id, s.title, s.duration_ms, ar.name AS artist_name, al.title AS album_title
FROM songs s
JOIN artists ar ON ar.id = s.artist_id
LEFT JOIN albums al ON al.id = s.album_id
WHERE s.deleted_at IS NULL
  AND ($1::text IS NULL OR s.title ILIKE '%' || $1::text || '%' OR ar.name ILIKE '%' || $1::text || '%')
ORDER BY
  CASE WHEN $2::bool THEN s.title END ASC,
  CASE WHEN NOT $2::bool THEN s.created_at END DESC
LIMIT $3
`

type ListLibrarySongsParams struct {
	Search     *string `json:"search"`
	SortAlpha  bool    `json:"sort_alpha"`
	LimitCount int32   `json:"limit_count"`
}

type ListLibrarySongsRow struct {
	ID         pgtype.UUID `json:"id"`
	Title      string      `json:"title"`
	DurationMs int32       `json:"duration_ms"`
	ArtistName string      `json:"artist_name"`
	AlbumTitle *string     `json:"album_title"`
}

// Sprint 14 sisipan — Browse Library (docs/screens-spec.md, ADR 0011):
// ALL of the catalog (not just favorites), with search + a simple sort
// toggle. No cursor pagination here (unlike most other list endpoints in
// this API) — a personal-scale library is realistically hundreds of
// items, not enough to need keyset pagination per sort mode; a flat
// LIMIT is simpler and correct at this scale.
func (q *Queries) ListLibrarySongs(ctx context.Context, arg ListLibrarySongsParams) ([]ListLibrarySongsRow, error) {
	rows, err := q.db.Query(ctx, listLibrarySongs, arg.Search, arg.SortAlpha, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLibrarySongsRow
	for rows.Next() {
		var i ListLibrarySongsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.DurationMs,
			&i.ArtistName,
			&i.AlbumTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
