// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lyrics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLyrics = `-- name: CreateLyrics :one
INSERT INTO lyrics (id, song_id, provider_id, synced_content, plain_content)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, song_id, provider_id, synced_content, plain_content, created_at
`

type CreateLyricsParams struct {
	ID            pgtype.UUID `json:"id"`
	SongID        pgtype.UUID `json:"song_id"`
	ProviderID    pgtype.UUID `json:"provider_id"`
	SyncedContent *string     `json:"synced_content"`
	PlainContent  *string     `json:"plain_content"`
}

func (q *Queries) CreateLyrics(ctx context.Context, arg CreateLyricsParams) (Lyric, error) {
	row := q.db.QueryRow(ctx, createLyrics,
		arg.ID,
		arg.SongID,
		arg.ProviderID,
		arg.SyncedContent,
		arg.PlainContent,
	)
	var i Lyric
	err := row.Scan(
		&i.ID,
		&i.SongID,
		&i.ProviderID,
		&i.SyncedContent,
		&i.PlainContent,
		&i.CreatedAt,
	)
	return i, err
}

const createLyricsProvider = `-- name: CreateLyricsProvider :one
INSERT INTO lyrics_providers (id, name, base_url)
VALUES ($1, $2, $3)
RETURNING id, name, base_url, is_enabled, priority, created_at, updated_at
`

type CreateLyricsProviderParams struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	BaseUrl string      `json:"base_url"`
}

func (q *Queries) CreateLyricsProvider(ctx context.Context, arg CreateLyricsProviderParams) (LyricsProvider, error) {
	row := q.db.QueryRow(ctx, createLyricsProvider, arg.ID, arg.Name, arg.BaseUrl)
	var i LyricsProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.IsEnabled,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLyricsBySongID = `-- name: GetLyricsBySongID :one
SELECT id, song_id, provider_id, synced_content, plain_content, created_at FROM lyrics WHERE song_id = $1
`

func (q *Queries) GetLyricsBySongID(ctx context.Context, songID pgtype.UUID) (Lyric, error) {
	row := q.db.QueryRow(ctx, getLyricsBySongID, songID)
	var i Lyric
	err := row.Scan(
		&i.ID,
		&i.SongID,
		&i.ProviderID,
		&i.SyncedContent,
		&i.PlainContent,
		&i.CreatedAt,
	)
	return i, err
}

const getLyricsProviderByName = `-- name: GetLyricsProviderByName :one
SELECT id, name, base_url, is_enabled, priority, created_at, updated_at FROM lyrics_providers WHERE name = $1
`

func (q *Queries) GetLyricsProviderByName(ctx context.Context, name string) (LyricsProvider, error) {
	row := q.db.QueryRow(ctx, getLyricsProviderByName, name)
	var i LyricsProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.IsEnabled,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
