// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	ID            pgtype.UUID        `json:"id"`
	ArtistID      pgtype.UUID        `json:"artist_id"`
	Title         string             `json:"title"`
	CoverUrl      *string            `json:"cover_url"`
	ReleasedAt    pgtype.Date        `json:"released_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	MusicbrainzID *string            `json:"musicbrainz_id"`
}

type Artist struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	ImageUrl      *string            `json:"image_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	MusicbrainzID *string            `json:"musicbrainz_id"`
}

type Device struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Name       string             `json:"name"`
	Type       string             `json:"type"`
	IsActive   bool               `json:"is_active"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Favorite struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	FavoritableType string             `json:"favoritable_type"`
	FavoritableID   pgtype.UUID        `json:"favoritable_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Genre struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

type IngestFilterRule struct {
	ID         pgtype.UUID        `json:"id"`
	SourceType string             `json:"source_type"`
	RuleType   string             `json:"rule_type"`
	Value      string             `json:"value"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type IngestJob struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	SourceType   string             `json:"source_type"`
	Status       string             `json:"status"`
	SongID       pgtype.UUID        `json:"song_id"`
	ErrorMessage *string            `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TempPath     *string            `json:"temp_path"`
}

type IngestSourceConnection struct {
	ID                   pgtype.UUID        `json:"id"`
	Provider             string             `json:"provider"`
	Label                string             `json:"label"`
	AccountEmail         *string            `json:"account_email"`
	CredentialsEncrypted string             `json:"credentials_encrypted"`
	IsActive             bool               `json:"is_active"`
	LastSyncedAt         pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Lyric struct {
	ID            pgtype.UUID        `json:"id"`
	SongID        pgtype.UUID        `json:"song_id"`
	ProviderID    pgtype.UUID        `json:"provider_id"`
	SyncedContent *string            `json:"synced_content"`
	PlainContent  *string            `json:"plain_content"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type LyricsProvider struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	BaseUrl           string             `json:"base_url"`
	IsEnabled         bool               `json:"is_enabled"`
	Priority          int32              `json:"priority"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	HealthStatus      string             `json:"health_status"`
	TotalLookups      int64              `json:"total_lookups"`
	SuccessfulMatches int64              `json:"successful_matches"`
}

type PlayHistory struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	SongID     pgtype.UUID        `json:"song_id"`
	ProgressMs int32              `json:"progress_ms"`
	PlayedAt   pgtype.Timestamptz `json:"played_at"`
}

type PlaybackState struct {
	UserID         pgtype.UUID        `json:"user_id"`
	ActiveDeviceID pgtype.UUID        `json:"active_device_id"`
	CurrentSongID  pgtype.UUID        `json:"current_song_id"`
	PositionMs     int32              `json:"position_ms"`
	IsPlaying      bool               `json:"is_playing"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Playlist struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	CoverUrl    *string            `json:"cover_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PlaylistSong struct {
	ID         pgtype.UUID        `json:"id"`
	PlaylistID pgtype.UUID        `json:"playlist_id"`
	SongID     pgtype.UUID        `json:"song_id"`
	Position   float64            `json:"position"`
	AddedAt    pgtype.Timestamptz `json:"added_at"`
}

type QueueItem struct {
	ID       pgtype.UUID        `json:"id"`
	UserID   pgtype.UUID        `json:"user_id"`
	SongID   pgtype.UUID        `json:"song_id"`
	Position float64            `json:"position"`
	AddedAt  pgtype.Timestamptz `json:"added_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	DeviceID  pgtype.UUID        `json:"device_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Song struct {
	ID            pgtype.UUID        `json:"id"`
	AlbumID       pgtype.UUID        `json:"album_id"`
	ArtistID      pgtype.UUID        `json:"artist_id"`
	StorageFileID pgtype.UUID        `json:"storage_file_id"`
	Title         string             `json:"title"`
	DurationMs    int32              `json:"duration_ms"`
	TrackNumber   *int32             `json:"track_number"`
	Checksum      string             `json:"checksum"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	WaveformPeaks []int16            `json:"waveform_peaks"`
	MusicbrainzID *string            `json:"musicbrainz_id"`
}

type SongGenre struct {
	SongID  pgtype.UUID `json:"song_id"`
	GenreID pgtype.UUID `json:"genre_id"`
}

type StorageAccount struct {
	ID                   pgtype.UUID        `json:"id"`
	Provider             string             `json:"provider"`
	Label                string             `json:"label"`
	AccountEmail         *string            `json:"account_email"`
	CredentialsEncrypted string             `json:"credentials_encrypted"`
	QuotaBytes           *int64             `json:"quota_bytes"`
	UsedBytes            int64              `json:"used_bytes"`
	IsActive             bool               `json:"is_active"`
	HealthStatus         string             `json:"health_status"`
	LastHealthCheckAt    pgtype.Timestamptz `json:"last_health_check_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type StorageFile struct {
	ID               pgtype.UUID        `json:"id"`
	StorageAccountID pgtype.UUID        `json:"storage_account_id"`
	ProviderFileID   string             `json:"provider_file_id"`
	Checksum         string             `json:"checksum"`
	SizeBytes        int64              `json:"size_bytes"`
	MimeType         string             `json:"mime_type"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	GoogleID  string             `json:"google_id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	AvatarUrl *string            `json:"avatar_url"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
