// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playback.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addQueueItem = `-- name: AddQueueItem :one
INSERT INTO queue_items (id, user_id, song_id, position)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, song_id, position, added_at
`

type AddQueueItemParams struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	SongID   pgtype.UUID `json:"song_id"`
	Position float64     `json:"position"`
}

func (q *Queries) AddQueueItem(ctx context.Context, arg AddQueueItemParams) (QueueItem, error) {
	row := q.db.QueryRow(ctx, addQueueItem,
		arg.ID,
		arg.UserID,
		arg.SongID,
		arg.Position,
	)
	var i QueueItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SongID,
		&i.Position,
		&i.AddedAt,
	)
	return i, err
}

const clearQueue = `-- name: ClearQueue :exec
DELETE FROM queue_items WHERE user_id = $1
`

func (q *Queries) ClearQueue(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearQueue, userID)
	return err
}

const getPlaybackState = `-- name: GetPlaybackState :one
SELECT user_id, active_device_id, current_song_id, position_ms, is_playing, updated_at FROM playback_states WHERE user_id = $1
`

func (q *Queries) GetPlaybackState(ctx context.Context, userID pgtype.UUID) (PlaybackState, error) {
	row := q.db.QueryRow(ctx, getPlaybackState, userID)
	var i PlaybackState
	err := row.Scan(
		&i.UserID,
		&i.ActiveDeviceID,
		&i.CurrentSongID,
		&i.PositionMs,
		&i.IsPlaying,
		&i.UpdatedAt,
	)
	return i, err
}

const listQueueByUser = `-- name: ListQueueByUser :many
SELECT id, user_id, song_id, position, added_at FROM queue_items WHERE user_id = $1 ORDER BY position ASC
`

func (q *Queries) ListQueueByUser(ctx context.Context, userID pgtype.UUID) ([]QueueItem, error) {
	rows, err := q.db.Query(ctx, listQueueByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueItem
	for rows.Next() {
		var i QueueItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SongID,
			&i.Position,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeQueueItem = `-- name: RemoveQueueItem :exec
DELETE FROM queue_items WHERE id = $1 AND user_id = $2
`

type RemoveQueueItemParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveQueueItem(ctx context.Context, arg RemoveQueueItemParams) error {
	_, err := q.db.Exec(ctx, removeQueueItem, arg.ID, arg.UserID)
	return err
}

const upsertPlaybackState = `-- name: UpsertPlaybackState :one
INSERT INTO playback_states (user_id, active_device_id, current_song_id, position_ms, is_playing, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (user_id) DO UPDATE SET
    active_device_id = EXCLUDED.active_device_id,
    current_song_id = EXCLUDED.current_song_id,
    position_ms = EXCLUDED.position_ms,
    is_playing = EXCLUDED.is_playing,
    updated_at = now()
RETURNING user_id, active_device_id, current_song_id, position_ms, is_playing, updated_at
`

type UpsertPlaybackStateParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	ActiveDeviceID pgtype.UUID `json:"active_device_id"`
	CurrentSongID  pgtype.UUID `json:"current_song_id"`
	PositionMs     int32       `json:"position_ms"`
	IsPlaying      bool        `json:"is_playing"`
}

func (q *Queries) UpsertPlaybackState(ctx context.Context, arg UpsertPlaybackStateParams) (PlaybackState, error) {
	row := q.db.QueryRow(ctx, upsertPlaybackState,
		arg.UserID,
		arg.ActiveDeviceID,
		arg.CurrentSongID,
		arg.PositionMs,
		arg.IsPlaying,
	)
	var i PlaybackState
	err := row.Scan(
		&i.UserID,
		&i.ActiveDeviceID,
		&i.CurrentSongID,
		&i.PositionMs,
		&i.IsPlaying,
		&i.UpdatedAt,
	)
	return i, err
}
