// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddQueueItem(ctx context.Context, arg AddQueueItemParams) (QueueItem, error)
	ClearQueue(ctx context.Context, userID pgtype.UUID) error
	CreateSong(ctx context.Context, arg CreateSongParams) (Song, error)
	DeleteSong(ctx context.Context, id pgtype.UUID) error
	GetPlaybackState(ctx context.Context, userID pgtype.UUID) (PlaybackState, error)
	// Used by the ingest pipeline for dedup before touching storage.
	GetSongByChecksum(ctx context.Context, checksum string) (Song, error)
	GetSongByID(ctx context.Context, id pgtype.UUID) (Song, error)
	ListQueueByUser(ctx context.Context, userID pgtype.UUID) ([]QueueItem, error)
	ListSongsByAlbum(ctx context.Context, albumID pgtype.UUID) ([]Song, error)
	ListSongsByArtist(ctx context.Context, arg ListSongsByArtistParams) ([]Song, error)
	RemoveQueueItem(ctx context.Context, arg RemoveQueueItemParams) error
	UpsertPlaybackState(ctx context.Context, arg UpsertPlaybackStateParams) (PlaybackState, error)
}

var _ Querier = (*Queries)(nil)
