// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddQueueItem(ctx context.Context, arg AddQueueItemParams) (QueueItem, error)
	AddSongGenre(ctx context.Context, arg AddSongGenreParams) error
	ClearIngestJobTempPath(ctx context.Context, id pgtype.UUID) error
	ClearQueue(ctx context.Context, userID pgtype.UUID) error
	ClearSongGenres(ctx context.Context, songID pgtype.UUID) error
	CompleteIngestJob(ctx context.Context, arg CompleteIngestJobParams) error
	CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error)
	CreateArtist(ctx context.Context, arg CreateArtistParams) (Artist, error)
	CreateGenre(ctx context.Context, arg CreateGenreParams) (Genre, error)
	CreateHistoryEntry(ctx context.Context, arg CreateHistoryEntryParams) (PlayHistory, error)
	CreateIngestFilterRule(ctx context.Context, arg CreateIngestFilterRuleParams) (IngestFilterRule, error)
	CreateIngestJob(ctx context.Context, arg CreateIngestJobParams) (IngestJob, error)
	CreateIngestSourceConnection(ctx context.Context, arg CreateIngestSourceConnectionParams) (IngestSourceConnection, error)
	CreateLyrics(ctx context.Context, arg CreateLyricsParams) (Lyric, error)
	CreateLyricsProvider(ctx context.Context, arg CreateLyricsProviderParams) (LyricsProvider, error)
	CreateSong(ctx context.Context, arg CreateSongParams) (Song, error)
	CreateStorageAccount(ctx context.Context, arg CreateStorageAccountParams) (StorageAccount, error)
	CreateStorageFile(ctx context.Context, arg CreateStorageFileParams) (StorageFile, error)
	DeleteIngestFilterRule(ctx context.Context, arg DeleteIngestFilterRuleParams) (int64, error)
	DeleteIngestJob(ctx context.Context, arg DeleteIngestJobParams) (int64, error)
	DeleteIngestSourceConnection(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteSong(ctx context.Context, id pgtype.UUID) error
	DeleteStorageAccount(ctx context.Context, id pgtype.UUID) (int64, error)
	FailIngestJob(ctx context.Context, arg FailIngestJobParams) error
	// Sprint 9: quota-aware routing — pick the active, non-down account with
	// the most free space. An account with no quota info yet (NULL, before
	// its first health check) is treated as having plenty of room rather
	// than excluded, so a brand new account isn't starved until checked.
	GetActiveStorageAccount(ctx context.Context) (StorageAccount, error)
	GetAlbumByArtistAndTitle(ctx context.Context, arg GetAlbumByArtistAndTitleParams) (Album, error)
	GetAlbumByID(ctx context.Context, id pgtype.UUID) (Album, error)
	GetAlbumDetail(ctx context.Context, id pgtype.UUID) (GetAlbumDetailRow, error)
	GetArtistByID(ctx context.Context, id pgtype.UUID) (Artist, error)
	GetArtistByName(ctx context.Context, name string) (Artist, error)
	GetBackgroundJobsSummary(ctx context.Context) ([]GetBackgroundJobsSummaryRow, error)
	GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error)
	GetGenreByName(ctx context.Context, name string) (Genre, error)
	GetIngestJobByID(ctx context.Context, id pgtype.UUID) (IngestJob, error)
	GetIngestSourceConnectionByID(ctx context.Context, id pgtype.UUID) (IngestSourceConnection, error)
	GetLyricsBySongID(ctx context.Context, songID pgtype.UUID) (Lyric, error)
	GetLyricsProviderByName(ctx context.Context, name string) (LyricsProvider, error)
	GetPlaybackState(ctx context.Context, userID pgtype.UUID) (PlaybackState, error)
	// Used by the ingest pipeline for dedup before touching storage.
	GetSongByChecksum(ctx context.Context, checksum string) (Song, error)
	GetSongByID(ctx context.Context, id pgtype.UUID) (Song, error)
	// Joined view used by the song detail endpoint and by the stream handler
	// (needs storage_file_id/provider_file_id/storage_account_id to fetch the
	// bytes from the storage provider).
	GetSongDetail(ctx context.Context, id pgtype.UUID) (GetSongDetailRow, error)
	GetStorageAccountByID(ctx context.Context, id pgtype.UUID) (StorageAccount, error)
	GetStorageFileByChecksum(ctx context.Context, checksum string) (StorageFile, error)
	// One row per month for the last 6 months (including the current one),
	// zero-filled via generate_series so a quiet month still shows up as a
	// bar at 0 instead of vanishing from the chart.
	GetStorageGrowth(ctx context.Context) ([]GetStorageGrowthRow, error)
	GetTopPlayedSongs(ctx context.Context, limit int32) ([]GetTopPlayedSongsRow, error)
	IncrementStorageAccountUsedBytes(ctx context.Context, arg IncrementStorageAccountUsedBytesParams) error
	ListActiveIngestSourceConnections(ctx context.Context) ([]IngestSourceConnection, error)
	// Sprint 14 admin Manage Songs (ADR 0010) — search by title or artist
	// name, same cursor-pagination shape used everywhere else in this API.
	ListAdminSongs(ctx context.Context, arg ListAdminSongsParams) ([]ListAdminSongsRow, error)
	ListAlbumsByArtist(ctx context.Context, artistID pgtype.UUID) ([]Album, error)
	// Sprint 14 admin Job Queue (docs/screens-spec.md #20) — same cursor
	// pattern as ListIngestJobsByUser, minus the per-user scoping.
	ListAllIngestJobs(ctx context.Context, arg ListAllIngestJobsParams) ([]IngestJob, error)
	// Sprint 10 garbage collector target: completed jobs still holding a
	// temp_path. Deliberately excludes 'failed' jobs — RetryJob needs that
	// file to still be on disk.
	ListCompletedIngestJobsWithTempPath(ctx context.Context, limit int32) ([]ListCompletedIngestJobsWithTempPathRow, error)
	// Most recent play per song, excluding songs barely started or basically
	// finished (both would be noise in a "continue listening" widget).
	ListContinueListening(ctx context.Context, arg ListContinueListeningParams) ([]ListContinueListeningRow, error)
	ListGenres(ctx context.Context) ([]Genre, error)
	ListHistoryByUser(ctx context.Context, arg ListHistoryByUserParams) ([]PlayHistory, error)
	ListIngestFilterRules(ctx context.Context, sourceType string) ([]IngestFilterRule, error)
	ListIngestJobsByUser(ctx context.Context, arg ListIngestJobsByUserParams) ([]IngestJob, error)
	ListIngestSourceConnections(ctx context.Context) ([]IngestSourceConnection, error)
	ListLibraryAlbums(ctx context.Context, arg ListLibraryAlbumsParams) ([]ListLibraryAlbumsRow, error)
	ListLibraryArtists(ctx context.Context, arg ListLibraryArtistsParams) ([]ListLibraryArtistsRow, error)
	// Sprint 14 sisipan — Browse Library (docs/screens-spec.md, ADR 0011):
	// ALL of the catalog (not just favorites), with search + a simple sort
	// toggle. No cursor pagination here (unlike most other list endpoints in
	// this API) — a personal-scale library is realistically hundreds of
	// items, not enough to need keyset pagination per sort mode; a flat
	// LIMIT is simpler and correct at this scale.
	ListLibrarySongs(ctx context.Context, arg ListLibrarySongsParams) ([]ListLibrarySongsRow, error)
	ListLyricsProviders(ctx context.Context) ([]LyricsProvider, error)
	ListQueueByUser(ctx context.Context, userID pgtype.UUID) ([]QueueItem, error)
	// Stand-in for "trending" until play_history exists (Sprint 6) to compute
	// real play-count trends.
	ListRecentSongs(ctx context.Context, limit int32) ([]ListRecentSongsRow, error)
	ListSongsByAlbum(ctx context.Context, albumID pgtype.UUID) ([]Song, error)
	ListSongsByArtist(ctx context.Context, arg ListSongsByArtistParams) ([]Song, error)
	ListStorageAccounts(ctx context.Context) ([]StorageAccount, error)
	ListStorageDistribution(ctx context.Context) ([]ListStorageDistributionRow, error)
	MarkIngestJobProcessing(ctx context.Context, id pgtype.UUID) error
	// Sprint 14: every GetLyrics attempt for a provider increments
	// total_lookups; matched only increments successful_matches too — this is
	// what makes "Match Rate" on the admin Lyrics Source page real instead of
	// fabricated (a miss previously left no trace at all).
	RecordLyricsLookup(ctx context.Context, arg RecordLyricsLookupParams) error
	RemoveQueueItem(ctx context.Context, arg RemoveQueueItemParams) error
	ResetIngestJobToPending(ctx context.Context, id pgtype.UUID) error
	SetLyricsProviderEnabled(ctx context.Context, arg SetLyricsProviderEnabledParams) error
	SetLyricsProviderHealth(ctx context.Context, arg SetLyricsProviderHealthParams) error
	// Sprint 14 sisipan (ADR 0008) — terminal state distinct from 'failed':
	// the item was never actually broken, it just didn't match a configured
	// filter rule for its source. temp_path is cleared same as a completed
	// job (ADR 0008: skipped items shouldn't linger as temp files either).
	SkipIngestJobByFilter(ctx context.Context, arg SkipIngestJobByFilterParams) error
	SoftDeleteSong(ctx context.Context, id pgtype.UUID) (int64, error)
	// musicbrainz_id always fills in; cover_url only fills in if still empty
	// (never overwrites a cover the user or an earlier match already set).
	UpdateAlbumMusicbrainzAndCover(ctx context.Context, arg UpdateAlbumMusicbrainzAndCoverParams) error
	// Only fills a still-empty musicbrainz_id — never overwrites a value set
	// by an earlier, possibly more specific match.
	UpdateArtistMusicbrainzID(ctx context.Context, arg UpdateArtistMusicbrainzIDParams) error
	UpdateIngestSourceConnectionSync(ctx context.Context, arg UpdateIngestSourceConnectionSyncParams) error
	UpdateLyricsProviderPriority(ctx context.Context, arg UpdateLyricsProviderPriorityParams) error
	UpdateQueueItemPosition(ctx context.Context, arg UpdateQueueItemPositionParams) (int64, error)
	UpdateSongArtistAlbum(ctx context.Context, arg UpdateSongArtistAlbumParams) error
	UpdateSongMusicbrainzID(ctx context.Context, arg UpdateSongMusicbrainzIDParams) error
	UpdateSongTitle(ctx context.Context, arg UpdateSongTitleParams) error
	UpdateSongWaveform(ctx context.Context, arg UpdateSongWaveformParams) error
	UpdateStorageAccountHealth(ctx context.Context, arg UpdateStorageAccountHealthParams) error
	UpsertPlaybackState(ctx context.Context, arg UpsertPlaybackStateParams) (PlaybackState, error)
}

var _ Querier = (*Queries)(nil)
