// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: songs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSong = `-- name: CreateSong :one
INSERT INTO songs (id, album_id, artist_id, storage_file_id, title, duration_ms, track_number, checksum)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, album_id, artist_id, storage_file_id, title, duration_ms, track_number, checksum, created_at, updated_at
`

type CreateSongParams struct {
	ID            pgtype.UUID `json:"id"`
	AlbumID       pgtype.UUID `json:"album_id"`
	ArtistID      pgtype.UUID `json:"artist_id"`
	StorageFileID pgtype.UUID `json:"storage_file_id"`
	Title         string      `json:"title"`
	DurationMs    int32       `json:"duration_ms"`
	TrackNumber   *int32      `json:"track_number"`
	Checksum      string      `json:"checksum"`
}

func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, createSong,
		arg.ID,
		arg.AlbumID,
		arg.ArtistID,
		arg.StorageFileID,
		arg.Title,
		arg.DurationMs,
		arg.TrackNumber,
		arg.Checksum,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ArtistID,
		&i.StorageFileID,
		&i.Title,
		&i.DurationMs,
		&i.TrackNumber,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSong = `-- name: DeleteSong :exec
DELETE FROM songs WHERE id = $1
`

func (q *Queries) DeleteSong(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSong, id)
	return err
}

const getSongByChecksum = `-- name: GetSongByChecksum :one
SELECT id, album_id, artist_id, storage_file_id, title, duration_ms, track_number, checksum, created_at, updated_at FROM songs WHERE checksum = $1
`

// Used by the ingest pipeline for dedup before touching storage.
func (q *Queries) GetSongByChecksum(ctx context.Context, checksum string) (Song, error) {
	row := q.db.QueryRow(ctx, getSongByChecksum, checksum)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ArtistID,
		&i.StorageFileID,
		&i.Title,
		&i.DurationMs,
		&i.TrackNumber,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSongByID = `-- name: GetSongByID :one
SELECT id, album_id, artist_id, storage_file_id, title, duration_ms, track_number, checksum, created_at, updated_at FROM songs WHERE id = $1
`

func (q *Queries) GetSongByID(ctx context.Context, id pgtype.UUID) (Song, error) {
	row := q.db.QueryRow(ctx, getSongByID, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.ArtistID,
		&i.StorageFileID,
		&i.Title,
		&i.DurationMs,
		&i.TrackNumber,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSongsByAlbum = `-- name: ListSongsByAlbum :many
SELECT id, album_id, artist_id, storage_file_id, title, duration_ms, track_number, checksum, created_at, updated_at FROM songs WHERE album_id = $1 ORDER BY track_number ASC NULLS LAST, title ASC
`

func (q *Queries) ListSongsByAlbum(ctx context.Context, albumID pgtype.UUID) ([]Song, error) {
	rows, err := q.db.Query(ctx, listSongsByAlbum, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.ArtistID,
			&i.StorageFileID,
			&i.Title,
			&i.DurationMs,
			&i.TrackNumber,
			&i.Checksum,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongsByArtist = `-- name: ListSongsByArtist :many
SELECT id, album_id, artist_id, storage_file_id, title, duration_ms, track_number, checksum, created_at, updated_at FROM songs
WHERE artist_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListSongsByArtistParams struct {
	ArtistID pgtype.UUID `json:"artist_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListSongsByArtist(ctx context.Context, arg ListSongsByArtistParams) ([]Song, error) {
	rows, err := q.db.Query(ctx, listSongsByArtist, arg.ArtistID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.ArtistID,
			&i.StorageFileID,
			&i.Title,
			&i.DurationMs,
			&i.TrackNumber,
			&i.Checksum,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
