// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStorageAccount = `-- name: CreateStorageAccount :one
INSERT INTO storage_accounts (id, provider, label, account_email, credentials_encrypted, quota_bytes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, provider, label, account_email, credentials_encrypted, quota_bytes, used_bytes, is_active, health_status, last_health_check_at, created_at, updated_at
`

type CreateStorageAccountParams struct {
	ID                   pgtype.UUID `json:"id"`
	Provider             string      `json:"provider"`
	Label                string      `json:"label"`
	AccountEmail         *string     `json:"account_email"`
	CredentialsEncrypted string      `json:"credentials_encrypted"`
	QuotaBytes           *int64      `json:"quota_bytes"`
}

func (q *Queries) CreateStorageAccount(ctx context.Context, arg CreateStorageAccountParams) (StorageAccount, error) {
	row := q.db.QueryRow(ctx, createStorageAccount,
		arg.ID,
		arg.Provider,
		arg.Label,
		arg.AccountEmail,
		arg.CredentialsEncrypted,
		arg.QuotaBytes,
	)
	var i StorageAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Label,
		&i.AccountEmail,
		&i.CredentialsEncrypted,
		&i.QuotaBytes,
		&i.UsedBytes,
		&i.IsActive,
		&i.HealthStatus,
		&i.LastHealthCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStorageFile = `-- name: CreateStorageFile :one
INSERT INTO storage_files (id, storage_account_id, provider_file_id, checksum, size_bytes, mime_type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, storage_account_id, provider_file_id, checksum, size_bytes, mime_type, created_at
`

type CreateStorageFileParams struct {
	ID               pgtype.UUID `json:"id"`
	StorageAccountID pgtype.UUID `json:"storage_account_id"`
	ProviderFileID   string      `json:"provider_file_id"`
	Checksum         string      `json:"checksum"`
	SizeBytes        int64       `json:"size_bytes"`
	MimeType         string      `json:"mime_type"`
}

func (q *Queries) CreateStorageFile(ctx context.Context, arg CreateStorageFileParams) (StorageFile, error) {
	row := q.db.QueryRow(ctx, createStorageFile,
		arg.ID,
		arg.StorageAccountID,
		arg.ProviderFileID,
		arg.Checksum,
		arg.SizeBytes,
		arg.MimeType,
	)
	var i StorageFile
	err := row.Scan(
		&i.ID,
		&i.StorageAccountID,
		&i.ProviderFileID,
		&i.Checksum,
		&i.SizeBytes,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveStorageAccount = `-- name: GetActiveStorageAccount :one
SELECT id, provider, label, account_email, credentials_encrypted, quota_bytes, used_bytes, is_active, health_status, last_health_check_at, created_at, updated_at FROM storage_accounts WHERE is_active = true ORDER BY created_at ASC LIMIT 1
`

// Sprint 3: pick the first active account, oldest first. No quota-aware
// routing yet — that's Sprint 9 (multi-drive pool).
func (q *Queries) GetActiveStorageAccount(ctx context.Context) (StorageAccount, error) {
	row := q.db.QueryRow(ctx, getActiveStorageAccount)
	var i StorageAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Label,
		&i.AccountEmail,
		&i.CredentialsEncrypted,
		&i.QuotaBytes,
		&i.UsedBytes,
		&i.IsActive,
		&i.HealthStatus,
		&i.LastHealthCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStorageFileByChecksum = `-- name: GetStorageFileByChecksum :one
SELECT id, storage_account_id, provider_file_id, checksum, size_bytes, mime_type, created_at FROM storage_files WHERE checksum = $1
`

func (q *Queries) GetStorageFileByChecksum(ctx context.Context, checksum string) (StorageFile, error) {
	row := q.db.QueryRow(ctx, getStorageFileByChecksum, checksum)
	var i StorageFile
	err := row.Scan(
		&i.ID,
		&i.StorageAccountID,
		&i.ProviderFileID,
		&i.Checksum,
		&i.SizeBytes,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}

const incrementStorageAccountUsedBytes = `-- name: IncrementStorageAccountUsedBytes :exec
UPDATE storage_accounts SET used_bytes = used_bytes + $2, updated_at = now() WHERE id = $1
`

type IncrementStorageAccountUsedBytesParams struct {
	ID        pgtype.UUID `json:"id"`
	UsedBytes int64       `json:"used_bytes"`
}

func (q *Queries) IncrementStorageAccountUsedBytes(ctx context.Context, arg IncrementStorageAccountUsedBytesParams) error {
	_, err := q.db.Exec(ctx, incrementStorageAccountUsedBytes, arg.ID, arg.UsedBytes)
	return err
}

const listStorageAccounts = `-- name: ListStorageAccounts :many
SELECT id, provider, label, account_email, credentials_encrypted, quota_bytes, used_bytes, is_active, health_status, last_health_check_at, created_at, updated_at FROM storage_accounts ORDER BY created_at ASC
`

func (q *Queries) ListStorageAccounts(ctx context.Context) ([]StorageAccount, error) {
	rows, err := q.db.Query(ctx, listStorageAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StorageAccount
	for rows.Next() {
		var i StorageAccount
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Label,
			&i.AccountEmail,
			&i.CredentialsEncrypted,
			&i.QuotaBytes,
			&i.UsedBytes,
			&i.IsActive,
			&i.HealthStatus,
			&i.LastHealthCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
